on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
jobs:
  check-upates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'misskey-dev /misskey'
          ref: 'develop'
          path: 'misskey'
      - uses: actions/checkout@v3
        with:
          ref: 'state'
